name: GitHub Actions Demo

on:
  push:
    branches:
      - ci-cd-set-up

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE: my-app
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Authorize Docker push
      run: |-
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud auth configure-docker gcr.io

    - name: Build and Push Container
      run: |-
        docker login -u _json_key -p "`cat {{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}`" https://gcr.io
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} ./
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.SERVICE }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        region: ${{ env.REGION }}

    - name: Redirect traffic to latest revision
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        revision_traffic: LATEST=100
